Practice/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Practice.Data;
using Practice.Helper;
using Practice.Models;
using Practice.Models.ViewModels;
using System.Security.Claims;

namespace Practice.Controllers
{
    public class AuthController : Controller
    {
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new CourseProject2DBContext())
                {
                    Сотрудники? employee = (from emp in db.Сотрудникиs
                                            where emp.Логин == model.Login
                                            select emp).FirstOrDefault();

                    if (employee == null || !Auth.VerifyHashedPassword(employee.Пароль, model.Password))
                    {
                        ModelState.AddModelError("Login", "Неправильный логин и/или пароль!");
                        ModelState.AddModelError("Password", "Неправильный логин и/или пароль!");
                        return View(model);
                    }

                    // создаем один claim
                    var claims = new List<Claim> { new Claim(ClaimsIdentity.DefaultNameClaimType, model.Login) };

                    // добавляем роли
                    foreach (var role in Queries.GetEmployeeRoles(model.Login))
                        claims.Add(new Claim(ClaimTypes.Role, role.Key));

                    // создаем объект ClaimsIdentity
                    ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
                    // установка аутентификационных куки
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                    return LocalRedirect("/");
                }
            }

            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
    }
}

Practice/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Practice.Data;
using Practice.Models;

namespace Practice.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            using (var db = new CourseProject2DBContext())
            {
                var query = (from emp in db.Сотрудникиs
                             join sex in db.Полs on emp.КодПола equals sex.Код
                             join empType in db.ВидыТрудоустройстваs on emp.КодВидаТрудоустройства equals empType.Код
                             where emp.Логин == User.Identity.Name
                             select new
                             {
                                 Фамилия = emp.Фамилия,
                                 Имя = emp.Имя,
                                 Отчество = emp.Отчество,
                                 Пол = sex.Пол1,
                                 ДатаРождения = emp.ДатаРождения.Value.Date.ToString(),
                                 Телефон1 = emp.Телефон1,
                                 Телефон2 = emp.Телефон2,
                                 ДатаНачалаРаботыВSap = emp.ДатаНачалаРаботыВSap.Value.Date.ToString(),
                                 ВидТрудоустройства = empType.ВидТрудоустройства,
                                 Логин = emp.Логин
                             }).FirstOrDefault();

                if (query == null)
                    return NotFound();

                var json_emp = JsonConvert.SerializeObject(query);
                var dict_emp = JsonConvert.DeserializeObject<Dictionary<string, string>>(json_emp);

                foreach (var key in dict_emp.Keys)
                {
                    if (dict_emp[key] == null || dict_emp[key] == "")
                        dict_emp[key] = "-";
                }

                return View(dict_emp);
            }
        }
    }
}

Practice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practice</title>
    <link rel="stylesheet" href="~/css/sandstoneBS.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practice.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">
                                Главная
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="d-flex">
                        @if (User.Identity.Name == null)
                        {
                            <a class="nav-link active text-light" asp-controller="Auth" asp-action="Login">
                                Вход
                            </a>
                        }
                        else
                        {
                            <a class="nav-link active text-light" asp-controller="Profile" asp-action="Index">
                                Профиль
                            </a>
                        }
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Курсовой проект 2 курс
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>