Practice/Models/ViewModels/DeveloperViewModel.cs
namespace Practice.Models.ViewModels
{
    public class DeveloperViewModel
    {
        public Dictionary<int, string> projects;
        public Dictionary<string, string> selectedProject;
        public List<Dictionary<string, string>> tasks;

        public DeveloperViewModel() { }
    }
}

Practice/Controllers/DeveloperController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Practice.Data;
using Practice.Models;
using Practice.Models.ViewModels;

namespace Practice.Controllers
{
    [Authorize(Roles = "Разработчик")]
    public class DeveloperController : Controller
    {
        private static Dictionary<int, string> GetEmployeeProjects(string login)
        {
            using (var db = new CourseProject2DBContext())
            {
                var projects = new Dictionary<int, string>();

                var query = (from pr_emp in db.ПроектыИСотрудникиs
                            join project in db.Проектыs on pr_emp.КодПроекта equals project.Код
                            join emp in db.Сотрудникиs on pr_emp.КодСотрудника equals emp.Код
                            where emp.Логин == login && project.ДатаЗавершенияПроекта == null 
                            && (pr_emp.ДатаОкончанияРаботыНаПроекте == null || pr_emp.ДатаОкончанияРаботыНаПроекте > DateTime.Now.Date)
                            orderby project.НазваниеПроекта
                            select new
                            {
                                Код = project.Код,
                                НазваниеПроекта = project.НазваниеПроекта
                            }).Distinct();

                foreach (var item in query)
                    projects.Add(item.Код ?? 0, item.НазваниеПроекта);

                return projects;
            }
        }

        private static Dictionary<string, string> GetSelectedProject(int projectId)
        {
            using (var db = new CourseProject2DBContext())
            {
                var query = (from project in db.Проектыs
                            join emp in db.Сотрудникиs on project.КодМенеджераПроекта equals emp.Код
                            join prType in db.ТипыПроектовs on project.КодТипаПроекта equals prType.Код
                            where project.Код == projectId
                            select new
                            {
                                Код = project.Код.ToString(),
                                НазваниеПроекта = project.НазваниеПроекта,
                                ДатаНачалаПроекта = project.ДатаНачалаПроекта.Value.Date.ToString(),
                                ДатаЗавершенияПроекта = project.ДатаЗавершенияПроекта.Value.Date.ToString(),
                                КодМенеджераПроекта = project.КодМенеджераПроекта.ToString(),
                                ФамилияМенеджераПроекта = emp.Фамилия,
                                ИмяМенеджераПроекта = emp.Имя,
                                ОтчествоМенеджераПроекта = emp.Отчество,
                                ТипПроекта = prType.ТипПроекта
                            }).FirstOrDefault();

                if (query == null)
                    return new Dictionary<string, string>();

                var json_pr = JsonConvert.SerializeObject(query);
                var dict_pr = JsonConvert.DeserializeObject<Dictionary<string, string>>(json_pr);

                return dict_pr;
            }
        }

        private static List<Dictionary<string, string>> GetEmployeeTasks(int projectId, string login)
        {
            using (var db = new CourseProject2DBContext())
            {
                var tasks = new List<Dictionary<string, string>>();

                var query = from task in db.ФактическиеТрудозатратыs
                            join status in db.Статусыs on task.КодСтатуса equals status.Код
                            join emp in db.Сотрудникиs on task.КодРазработчика equals emp.Код
                            where task.КодПроекта == projectId && emp.Логин == login
                            orderby status.Код, task.ПоследнееИзменение descending
                            select new
                            {
                                Код = task.Код.ToString(),
                                Задача = task.Задача,
                                ДатаТрудозатраты = task.ДатаТрудозатраты.Value.Date.ToString(),
                                КоличествоЧасов = task.КоличествоЧасов.ToString(),
                                Статус = status.Статус,
                                Комментарий = task.Комментарий,
                                ПоследнееИзменение = task.ПоследнееИзменение.ToString("yyyy-MM-dd HH:mm:ss")
                            };

                foreach (var item in query)
                {
                    var json_task = JsonConvert.SerializeObject(item);
                    var dict_task = JsonConvert.DeserializeObject<Dictionary<string, string>>(json_task);

                    tasks.Add(dict_task);
                }

                if (tasks.Count == 0)
                {
                    var list = new List<Dictionary<string, string>>();
                    var dict = new Dictionary<string, string>();
                    var keys = new string[] { "Код", "Задача", "ДатаТрудозатраты", "КоличествоЧасов", "Статус", "Комментарий", "ПоследнееИзменение" };

                    foreach (var key in keys)
                        dict.Add(key, null);

                    list.Add(dict);

                    return list;
                }

                return tasks;
            }
        }

        [HttpGet]
        public IActionResult Index(int projectId = -1)
        {
            var projects = GetEmployeeProjects(User.Identity.Name);

            if (projectId == -1)
                return View(new DeveloperViewModel() { projects = projects });
            else if (!projects.Keys.Contains(projectId))
                return NotFound();

            return View(new DeveloperViewModel() { projects = projects, selectedProject = GetSelectedProject(projectId), tasks = GetEmployeeTasks(projectId, User.Identity.Name) });
        }

        [HttpGet]
        public IActionResult AddTask(int id = -1)
        {
            if (id == -1)
                return NotFound();

            ViewBag.ProjectId = id;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddTask(ФактическиеТрудозатраты task)
        {
            using (var db = new CourseProject2DBContext())
            {
                if (ModelState.ErrorCount == 5)
                {
                    long empId = (from emp in db.Сотрудникиs
                                  where emp.Логин == User.Identity.Name
                                  select emp.Код).First();

                    task.КодРазработчика = empId;
                    task.КодСтатуса = 3;
                    task.ПоследнееИзменение = DateTime.Now;

                    db.ФактическиеТрудозатратыs.Add(task);
                    db.SaveChanges();

                    return RedirectToAction("Index", new { projectid = task.КодПроекта });
                }
            }

            return View(task);
        }

        [HttpGet]
        public IActionResult UpdateTask(long id = -1)
        {
            if (id == -1)
                return NotFound();

            using (var db = new CourseProject2DBContext())
            {
                var task = db.ФактическиеТрудозатратыs.Find(id);

                if (task == null || task.КодСтатуса == 2)
                    return NotFound();

                ViewBag.ProjectId = task.КодПроекта;
                ViewBag.TaskId = task.Код;

                return View(task);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateTask(ФактическиеТрудозатраты task)
        {
            using (var db = new CourseProject2DBContext())
            {
                if (ModelState.ErrorCount == 4)
                {
                    long empId = (from emp in db.Сотрудникиs
                                  where emp.Логин == User.Identity.Name
                                  select emp.Код).First();

                    task.КодРазработчика = empId;
                    task.КодСтатуса = 3;
                    task.ПоследнееИзменение = DateTime.Now;

                    db.ФактическиеТрудозатратыs.Update(task);
                    db.SaveChanges();
                    TempData["success"] = "Category updated successfully";

                    return RedirectToAction("Index", new { projectid = task.КодПроекта });
                }
            }

            return View(task);
        }

        [HttpGet]
        public IActionResult DeleteTask(long id = -1)
        {
            if (id == -1)
                return NotFound();

            using (var db = new CourseProject2DBContext())
            {
                var task = db.ФактическиеТрудозатратыs.Find(id);

                if (task == null || task.КодСтатуса == 2)
                    return NotFound();

                ViewBag.ProjectId = task.КодПроекта;
                ViewBag.TaskId = task.Код;

                return View(task);
            }
        }

        [HttpPost, ActionName("DeleteTask")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteTaskPOST(long id = -1)
        {
            using (var db = new CourseProject2DBContext())
            {
                var task = db.ФактическиеТрудозатратыs.Find(id);

                if (task == null)
                    return NotFound();

                db.ФактическиеТрудозатратыs.Remove(task);
                db.SaveChanges();

                return RedirectToAction("Index", new { projectid = task.КодПроекта });
            }
        }
    }
}

Practice/Views/Developer/AddTask.cshtml
@model ФактическиеТрудозатраты
@{
    ViewData["Title"] = "AddTask";
}

<form method="post">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Добавление трудозатраты</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Задача">Задача</label>
                <input asp-for="Задача" class="form-control" />
                <span asp-validation-for="Задача" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ДатаТрудозатраты">Дата трудозатраты</label>
                <input asp-for="ДатаТрудозатраты" class="form-control" />
                <span asp-validation-for="ДатаТрудозатраты" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="КоличествоЧасов">Количество часов</label>
                <input asp-for="КоличествоЧасов" class="form-control" />
                <span asp-validation-for="КоличествоЧасов" class="text-danger"></span>
            </div>

            <input asp-for="КодПроекта" class="form-control d-none" value=@ViewBag.ProjectId />
            
            <div class="text-end">
                <a asp-controller="Developer" asp-action="Index" asp-route-projectid=@ViewBag.ProjectId class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Добавить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/Developer/DeleteTask.cshtml
@model ФактическиеТрудозатраты
@{
    ViewData["Title"] = "DeleteTask";
}

<form method="post" asp-action="DeleteTask">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Удаление трудозатраты</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Задача">Задача</label>
                <input asp-for="Задача" class="form-control" readonly />
            </div>
            <div class="mb-3">
                <label asp-for="ДатаТрудозатраты">Дата трудозатраты</label>
                <input asp-for="ДатаТрудозатраты" class="form-control" readonly />
            </div>
            <div class="mb-3">
                <label asp-for="КоличествоЧасов">Количество часов</label>
                <input asp-for="КоличествоЧасов" class="form-control" readonly />
            </div>

            <input asp-for="КодПроекта" class="form-control d-none" value=@ViewBag.ProjectId />
            <input asp-for="Код" class="form-control d-none" value=@ViewBag.TaskId />
            
            <div class="text-end">
                <a asp-controller="Developer" asp-action="Index" asp-route-projectid=@ViewBag.ProjectId class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Удалить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/Developer/Index.cshtml
@using Practice.Models.ViewModels
@model DeveloperViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <h1 class="mt-3 mb-3">Разработчик</h1>
</div>

<div class="row">
    <div class="col-1">
        <a class="nav-link dropdown-toggle active text-dark h4" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Проекты</a>
        <div class="dropdown-menu">
            @foreach (var item in Model.projects)
            {
                <a class="dropdown-item" asp-controller="Developer" asp-action="Index" asp-route-projectid=@item.Key>@item.Value</a>
            }
        </div>
    </div>

    <div class="col-10">
        @if (Model.selectedProject != null)
        {
            <h4 class="mt-2">@Model.selectedProject["НазваниеПроекта"]</h4>
        }

        <div>
            <table class="table align-middle">
                <thead>
                    @if (Model.selectedProject != null)
                    {
                        <tr>
                            @foreach (var item in Model.selectedProject.Keys)
                            {
                                <th scope="col">@item</th>
                            }
                        </tr>
                    }
                </thead>
                <tbody>
                    @if (Model.selectedProject != null)
                    {
                        <tr>
                            @foreach (var item in Model.selectedProject.Values)
                            {
                                <th scope="col">@item</th>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        @if (Model.selectedProject != null)
        {
            <h4 class="mt-5">Трудозатраты</h4>
        }
        <div>
            <table class="table align-middle table-responsive fixed-table">
                <thead>
                    @if (Model.tasks != null)
                    {
                        <tr>
                            @foreach (var item in Model.tasks[0])
                            {
                                <th scope="col">@item.Key</th>
                            }
                            <th scope="col"></th>
                        </tr>
                    }
                </thead>
                <tbody>
                    @if (Model.tasks != null)
                    {
                        @foreach (var item in Model.tasks)
                        {
                            @switch (item["Статус"])
                            {
                                case "Не подтверждено":
                                    <tr class="table-danger">

                                        @foreach (var col in item)
                                        {
                                            <td><p>@col.Value</p></td>
                                        }

                                        @if (item["Код"] != null)
                                        {
                                            <td class="text-end" nowrap>
                                                <a asp-controller="Developer" asp-action="UpdateTask" asp-route-id=@int.Parse(item["Код"]) class="btn btn-dark"><i class="bi bi-pencil-fill"></i></a>
                                                <a asp-controller="Developer" asp-action="DeleteTask" asp-route-id=@int.Parse(item["Код"]) class="btn btn-dark"><i class="bi bi-trash3-fill"></i></a>
                                            </td>
                                        }
                                    </tr>

                                    break;
                                case "Подтверждено":
                                    <tr class="table-success">

                                        @foreach (var col in item)
                                        {
                                            <td><p>@col.Value</p></td>
                                        }

                                        @if (item["Код"] != null)
                                        {
                                            <td class="text-end" nowrap>
                                                <a asp-controller="Developer" asp-action="UpdateTask" asp-route-id=@int.Parse(item["Код"]) class="btn btn-dark disabled"><i class="bi bi-pencil-fill"></i></a>
                                                <a asp-controller="Developer" asp-action="DeleteTask" asp-route-id=@int.Parse(item["Код"]) class="btn btn-dark disabled"><i class="bi bi-trash3-fill"></i></a>
                                            </td>
                                        }
                                    </tr>

                                    break;
                                default:
                                    <tr>

                                        @foreach (var col in item)
                                        {
                                            <td><p>@col.Value</p></td>
                                        }

                                        @if (item["Код"] != null)
                                        {
                                            <td class="text-end" nowrap>
                                                <a asp-controller="Developer" asp-action="UpdateTask" asp-route-id=@int.Parse(item["Код"]) class="btn btn-dark"><i class="bi bi-pencil-fill"></i></a>
                                                <a asp-controller="Developer" asp-action="DeleteTask" asp-route-id=@int.Parse(item["Код"]) class="btn btn-dark"><i class="bi bi-trash3-fill"></i></a>
                                            </td>
                                        }
                                    </tr>

                                    break;
                            }
                        }
                    }
                </tbody>
            </table>
        </div>

        @if (Model.selectedProject != null)
        {
            <div class="text-end">
                <a asp-controller="Developer" asp-action="AddTask" asp-route-id=@int.Parse(Model.selectedProject["Код"]) class="btn btn-dark">
                    Добавить трудозатрату
                </a>
            </div>
        }
    </div>

    <div class="col-1"></div>
</div>

Practice/Views/Developer/UpdateTask.cshtml
@model ФактическиеТрудозатраты
@{
    ViewData["Title"] = "UpdateTask";
}

<form method="post" asp-action="UpdateTask">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Редактирование трудозатраты</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Задача">Задача</label>
                <input asp-for="Задача" class="form-control" />
                <span asp-validation-for="Задача" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ДатаТрудозатраты">Дата трудозатраты</label>
                <input asp-for="ДатаТрудозатраты" class="form-control" />
                <span asp-validation-for="ДатаТрудозатраты" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="КоличествоЧасов">Количество часов</label>
                <input asp-for="КоличествоЧасов" class="form-control" />
                <span asp-validation-for="КоличествоЧасов" class="text-danger"></span>
            </div>

            <input asp-for="КодПроекта" class="form-control d-none" value=@ViewBag.ProjectId />
            <input asp-for="Код" class="form-control d-none" value=@ViewBag.TaskId />
            
            <div class="text-end">
                <a asp-controller="Developer" asp-action="Index" asp-route-projectid=@ViewBag.ProjectId class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Обновить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>