Practice/Models/ViewModels/ProjectManagerViewModel.cs
namespace Practice.Models.ViewModels
{
    public class ProjectManagerViewModel
    {
        public Dictionary<int, string> projects;
        public Dictionary<string, string> selectedProject;
        public List<Dictionary<string, string>> employees;

        public ProjectManagerViewModel() { }
    }
}

Practice/Controllers/ProjectManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Practice.Data;
using Practice.Helper;
using Practice.Models;
using Practice.Models.ViewModels;

namespace Practice.Controllers
{
    [Authorize(Roles = "Менеджер проекта")]
    public class ProjectManagerController : Controller
    {
        private static Dictionary<int, string> GetProjectManagerProjects(string login)
        {
            using (var db = new CourseProject2DBContext())
            {
                var projects = new Dictionary<int, string>();

                var query = from project in db.Проектыs
                            join emp in db.Сотрудникиs on project.КодМенеджераПроекта equals emp.Код
                            where emp.Логин == login && project.ДатаЗавершенияПроекта == null
                            orderby project.НазваниеПроекта
                            select new
                            {
                                Код = project.Код,
                                НазваниеПроекта = project.НазваниеПроекта
                            };

                foreach (var item in query)
                    projects.Add(item.Код ?? 0, item.НазваниеПроекта);

                return projects;
            }
        }

        private static Dictionary<string, string> GetSelectedProject(int projectId)
        {
            using (var db = new CourseProject2DBContext())
            {
                var query = (from project in db.Проектыs
                             join emp in db.Сотрудникиs on project.КодМенеджераПроекта equals emp.Код
                             join prType in db.ТипыПроектовs on project.КодТипаПроекта equals prType.Код
                             where project.Код == projectId
                             select new
                             {
                                 Код = project.Код.ToString(),
                                 НазваниеПроекта = project.НазваниеПроекта,
                                 ДатаНачалаПроекта = project.ДатаНачалаПроекта.Value.Date.ToString(),
                                 ДатаЗавершенияПроекта = project.ДатаЗавершенияПроекта.Value.Date.ToString(),
                                 КодМенеджераПроекта = project.КодМенеджераПроекта.ToString(),
                                 ФамилияМенеджераПроекта = emp.Фамилия,
                                 ИмяМенеджераПроекта = emp.Имя,
                                 ОтчествоМенеджераПроекта = emp.Отчество,
                                 ТипПроекта = prType.ТипПроекта
                             }).First();

                var json_pr = JsonConvert.SerializeObject(query);
                var dict_pr = JsonConvert.DeserializeObject<Dictionary<string, string>>(json_pr);

                return dict_pr;
            }
        }

        private static List<Dictionary<string, string>> GetProjectDevelopers(int projectId)
        {
            using (var db = new CourseProject2DBContext())
            {
                var devs = new List<Dictionary<string, string>>();

                var query = from pr_emp in db.ПроектыИСотрудникиs
                            join emp in db.Сотрудникиs on pr_emp.КодСотрудника equals emp.Код
                            join role in db.Ролиs on pr_emp.КодРоли equals role.Код
                            where pr_emp.КодПроекта == projectId && (pr_emp.ДатаОкончанияРаботыНаПроекте > DateTime.Now || pr_emp.ДатаОкончанияРаботыНаПроекте == null)
                            select new
                            {
                                Код = emp.Код,
                                Фамилия = emp.Фамилия,
                                Имя = emp.Имя,
                                Отчество = emp.Отчество,
                                Логин = emp.Логин,
                                Роль = role.Роль,
                                ДатаНачалаРаботыНаПроекте = pr_emp.ДатаНачалаРаботыНаПроекте.Value.ToString("yyyy-MM-dd HH:mm:ss"),
                                ДатаОкончанияРаботыНаПроекте = pr_emp.ДатаОкончанияРаботыНаПроекте.Value.ToString("yyyy-MM-dd HH:mm:ss")
                            };

                var query1 = from rate in db.СтавкиСотрудниковs
                             where rate.КодПроекта == projectId && rate.ДатаНачалаДействияСтавки <= DateTime.Now
                             group rate by rate.КодСотрудника into g
                             select new
                             {
                                 Код = g.Where(x => x.ДатаНачалаДействияСтавки == g.Max(s => s.ДатаНачалаДействияСтавки)).Select(a => a.Код).First(),
                                 КодСотрудника = g.Key,
                                 ДатаНачалаДействияСтавки = g.Max(s => s.ДатаНачалаДействияСтавки)
                             };

                var query2 = from item in query1
                             join rate in db.СтавкиСотрудниковs on item.Код equals rate.Код
                             select new
                             {
                                 КодСотрудника = item.КодСотрудника,
                                 ДатаНачалаДействияСтавки = item.ДатаНачалаДействияСтавки,
                                 Ставка = rate.Ставка
                             };

                var resultQuery = from emp in query
                                  join item2 in query2 on emp.Код equals item2.КодСотрудника into gr
                                  from g in gr.DefaultIfEmpty()
                                  select new
                                  {
                                      Код = emp.Код.ToString(),
                                      Фамилия = emp.Фамилия,
                                      Имя = emp.Имя,
                                      Отчество = emp.Отчество,
                                      Логин = emp.Логин,
                                      Роль = emp.Роль,
                                      ДатаНачалаРаботыНаПроекте = emp.ДатаНачалаРаботыНаПроекте,
                                      ДатаОкончанияРаботыНаПроекте = emp.ДатаОкончанияРаботыНаПроекте,
                                      ДатаНачалаДействияСтавки = g.ДатаНачалаДействияСтавки.Value.ToString("yyyy-MM-dd HH:mm:ss") ?? string.Empty,
                                      Ставка = g.Ставка.ToString() ?? string.Empty
                                  };

                foreach (var item in resultQuery)
                {
                    var json_emps = JsonConvert.SerializeObject(item);
                    var dict_emps = JsonConvert.DeserializeObject<Dictionary<string, string>>(json_emps);

                    devs.Add(dict_emps);
                }

                if (devs.Count == 0)
                {
                    var list = new List<Dictionary<string, string>>();
                    var dict = new Dictionary<string, string>();
                    var keys = new string[] { "Код", "Фамилия", "Имя", "Отчество", "Логин", "Роль", "ДатаНачалаРаботыНаПроекте", "ДатаОкончанияРаботыНаПроекте", "ДатаНачалаДействияСтавки", "Ставка" };

                    foreach (var key in keys)
                        dict.Add(key, null);

                    list.Add(dict);

                    return list;
                }

                return devs;
            }
        }

        public IActionResult Index(int projectId = -1)
        {
            var projects = GetProjectManagerProjects(User.Identity.Name);

            if (projectId == -1)
                return View(new ProjectManagerViewModel() { projects = projects });
            else if (!projects.Keys.Contains(projectId))
                return NotFound();

            return View(new ProjectManagerViewModel() { projects = projects, selectedProject = GetSelectedProject(projectId), employees = GetProjectDevelopers(projectId) });
        }

        [HttpGet]
        public IActionResult AvailableEmployees(int projectId = -1)
        {
            if (projectId == -1)
                return NotFound();

            using (var db = new CourseProject2DBContext())
            {
                var devs = new List<Dictionary<string, string>>();
                List<long> projectDevs = new List<long>();
                var prDev = GetProjectDevelopers(projectId);

                if (prDev[0]["Код"] != null)
                {
                    foreach (var dev in GetProjectDevelopers(projectId))
                        projectDevs.Add(long.Parse(dev["Код"]));
                }

                var query = (from emp in db.Сотрудникиs
                             join sex in db.Полs on emp.КодПола equals sex.Код
                             join empType in db.ВидыТрудоустройстваs on emp.КодВидаТрудоустройства equals empType.Код
                             join pr_emp in db.ПроектыИСотрудникиs on emp.Код equals pr_emp.КодСотрудника into gr
                             from g in gr.DefaultIfEmpty()
                             where !projectDevs.Contains(emp.Код) && emp.Логин != User.Identity.Name
                             && (
                             from employee in db.УстройствоНаРаботуs
                             where employee.ДатаУвольнения > DateTime.Now.Date || employee.ДатаУвольнения == null
                             select employee.КодСотрудника).ToList().Contains(emp.Код)
                             && (from emp_pos in db.ДолжностиСотрудниковs
                                 join pos in db.Должностиs on emp_pos.КодДолжности equals pos.Код
                                 where Queries.developerTypes.Contains(pos.Должность)
                                 select emp_pos.КодСотрудника).Contains(emp.Код)
                             select new
                             {
                                 Код = emp.Код.ToString(),
                                 Фамилия = emp.Фамилия,
                                 Имя = emp.Имя,
                                 Отчество = emp.Отчество,

Practice/Views/ProjectManager/AddDeveloper.cshtml
@using Practice.Data;
@model ПроектыИСотрудники
@{
    ViewData["Title"] = "AddDeveloper";

    using (var db = new CourseProject2DBContext())
    {
        ViewBag.Roles = (from role in db.Ролиs select role).ToList();
    }
}

<div class="row">
    <h1 class="mt-3 mb-3">Менеджер проекта</h1>
</div>

<form method="post">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Добавить разработчика</h2>
                <hr />
            </div>
            <div class="mb-3">
                <select class="form-control" asp-for="КодРоли">
                    <option selected>Выбрать роль...</option>
                    @foreach (var role in ViewBag.Roles)
                    {
                        <option value=@role.Код>@role.Роль</option>
                    }
                </select>
                <span asp-validation-for="КодРоли" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ДатаНачалаРаботыНаПроекте">Дата начала работы на проекте</label>
                <input asp-for="ДатаНачалаРаботыНаПроекте" class="form-control" />
                <span asp-validation-for="ДатаНачалаРаботыНаПроекте" class="text-danger"></span>
            </div>

            <input asp-for="КодСотрудника" class="form-control d-none" value=@ViewBag.Id />
            <input asp-for="КодПроекта" class="form-control d-none" value=@ViewBag.ProjectId />

            <div class="text-end">
                <a asp-controller="ProjectManager" asp-action="AvailableEmployees" asp-route-projectid=@ViewBag.ProjectId class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Добавить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/ProjectManager/AvailableEmployees.cshtml
@model List<Dictionary<string, string>>
@{
    ViewData["Title"] = "AvailableEmployees";
}

<div class="row">
    <h1 class="mt-3 mb-3">Менеджер проекта</h1>
</div>

<div class="row">
    <div class="col-1"></div>
    <div class="col-10">
        <h4 class="mt-2">Доступные сотрудники</h4>
        <table class="table table-striped align-middle table-responsive fixed-table">
            <thead>
                <tr>
                    @foreach (var item in Model[0])
                    {
                        <th scope="col">@item.Key</th>
                    }
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        @foreach (var col in item)
                        {
                            <td><p class="my-0">@col.Value</p></td>
                        }

                        @if (item["Код"] != null)
                        {
                            <td class="text-center" nowrap>
                                <a asp-controller="ProjectManager" asp-action="AddDeveloper" asp-route-id=@int.Parse(item["Код"]) asp-route-projectid=@ViewBag.ProjectId>
                                    <i class="bi bi-plus-circle" style="font-size: 1.5rem; color:black;"></i>
                                </a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        <div class="text-end">
                <a asp-controller="ProjectManager" asp-action="Index" asp-route-projectid=@ViewBag.ProjectId class="btn btn-secondary">
                    Назад
                </a>
            </div>
    </div>
    <div class="col-1"></div>
</div>

Practice/Views/ProjectManager/CheckTask.cshtml
@model ФактическиеТрудозатраты
@{
    ViewData["Title"] = "CheckTask";
}

<div class="row">
    <h1 class="mt-3 mb-3">Менеджер проекта</h1>
</div>

<form method="post" asp-action="CheckTask">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2 class="text_primary">Проверка трудозатраты</h2>
                <hr />
            </div>
            <div asp-validation-summary="All"></div>

            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="КодРазработчика">Код разработчика</label>
                <input asp-for="КодРазработчика" class="form-control" value=@Model.КодРазработчика readonly />
            </div>
            <div class="mb-3">
                <label asp-for="КодПроекта">Код проекта</label>
                <input asp-for="КодПроекта" class="form-control" value=@Model.КодПроекта readonly />
            </div>
            <div class="mb-3">
                <label asp-for="Задача">Задача</label>
                <input asp-for="Задача" class="form-control" value=@Model.Задача readonly />
            </div>
            <div class="mb-3">
                <label asp-for="ДатаТрудозатраты">Дата трудозатраты</label>
                <input asp-for="ДатаТрудозатраты" class="form-control" type="datetime" value=@Model.ДатаТрудозатраты readonly />
            </div>
            <div class="mb-3">
                <label asp-for="КодСтатуса">Код статуса</label>
                <input asp-for="КодСтатуса" class="form-control" value=@Model.КодСтатуса readonly />
            </div>
            <div class="mb-3">
                <label asp-for="КоличествоЧасов">Количество часов</label>
                <input asp-for="КоличествоЧасов" class="form-control" value=@Model.КоличествоЧасов readonly />
            </div>
            <div class="mb-3">
                <label asp-for="ПоследнееИзменение">Последнее изменение</label>
                <input asp-for="ПоследнееИзменение" class="form-control" type="datetime" value=@Model.ПоследнееИзменение readonly />
            </div>

            <div class="mb-3">
                <label asp-for="Комментарий">Комментарий</label>
                <input asp-for="Комментарий" class="form-control" />
                <span asp-validation-for="Комментарий" class="text_danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="ProjectManager" asp-action="GetAllTasks" asp-route-projectid=@Model.КодПроекта class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Отправить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/ProjectManager/GetAllRates.cshtml
@model List<СтавкиСотрудников>
@{
    ViewData["Title"] = "GetAllRates";
}

<div class="row">
    <h1 class="mt-3 mb-3">Менеджер проекта</h1>
</div>

<div class="row align-middle">
    <div class="col-2"></div>

    <div class="col-8">
        <table class="table table-al table-striped align-middle">
            <thead>
                <tr>
                    <th scope="col">Дата начала действия ставки</th>
                    <th scope="col">Ставка</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ДатаНачалаДействияСтавки</td>
                        <td>@item.Ставка</td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="text-end">
            <a asp-controller="ProjectManager" asp-action="UpdateDeveloper" asp-route-id=@ViewBag.Id asp-route-projectid=@ViewBag.ProjectId class="btn btn-secondary mx-3" style="width:150px">
                Назад
            </a>
        </div>
    </div>

    <div class="col-2"></div>
</div>

Practice/Views/ProjectManager/GetAllTasks.cshtml
@model List<Dictionary<string, string>>
@{
    ViewData["Title"] = "GetAllTasks";
}

<div class="row">
    <h1 class="mt-3 mb-3">Менеджер проекта</h1>
</div>

<div class="row">
    <div class="col-1"></div>
    <div class="col-10">
        <h4 class="mt-2">Трудозатраты всех разработчиков проекта</h4>
        <table class="table table-striped align-middle table-responsive fixed-table">
            <thead>
                <tr>
                    @if (Model != null)
                    {
                        @foreach (var item in Model[0])
                        {
                            <th scope="col">@item.Key</th>
                        }
                    }
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            @foreach (var col in item)
                            {
                                <td><p class="my-0">@col.Value</p></td>
                            }

                            @if (item["КодРазработчика"] != null)
                            {
                                <td class="text-center" nowrap>
                                    <a asp-controller="ProjectManager" asp-action="CheckTask" asp-route-projectid=@ViewBag.ProjectId asp-route-taskid=@item["Код"] asp-route-statusid=2 style="color: white;">
                                        <i class="bi bi-check2 px-2" style="font-size: 1.75rem; color:black;"></i>
                                    </a>
                                    <a asp-controller="ProjectManager" asp-action="CheckTask" asp-route-projectid=@ViewBag.ProjectId asp-route-taskid=@item["Код"] asp-route-statusid=1>
                                        <i class="bi bi-x-lg" style="font-size: 1.75rem; color:black;"></i>
                                    </a>
                                </td>
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
        <div class="text-end">
            <a asp-controller="ProjectManager" asp-action="Index" asp-route-projectid=@ViewBag.ProjectId class="btn btn-secondary">
                Назад
            </a>
        </div>
    </div>
    <div class="col-1"></div>
</div>

Practice/Views/ProjectManager/Index.cshtml
@using Practice.Models.ViewModels
@model ProjectManagerViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <h1 class="mt-3 mb-3">Менеджер проекта</h1>
</div>

<div class="row">
    <div class="col-1">
        <a class="nav-link dropdown-toggle active text-dark h4" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Проекты</a>
        <div class="dropdown-menu">
            @foreach (var item in Model.projects)
            {
                <a class="dropdown-item" asp-controller="ProjectManager" asp-action="Index" asp-route-projectid=@item.Key>@item.Value</a>
            }
        </div>
    </div>

    <div class="col-10">
        @if (Model.selectedProject != null)
        {
            <h4 class="mt-2">@Model.selectedProject["НазваниеПроекта"]</h4>
        }
        <div>
            <table class="table align-middle">
                <thead>
                    @if (Model.selectedProject != null)
                    {
                        <tr>
                            @foreach (var item in Model.selectedProject.Keys)
                            {
                                <th scope="col">@item</th>
                            }
                        </tr>
                    }
                </thead>
                <tbody>
                    @if (Model.selectedProject != null)
                    {
                        <tr>
                            @foreach (var item in Model.selectedProject.Values)
                            {
                                <td><p>@item</p></td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        @if (Model.selectedProject != null)
        {
            <h4 class="mt-5">Разработчики</h4>
        }
        <div>
            <table class="table table-striped align-middle table-responsive fixed-table">
                <thead>
                    @if (Model.employees != null)
                    {
                        <tr>
                            @foreach (var item in Model.employees[0])
                            {
                                <th scope="col">@item.Key</th>
                            }
                            <th scope="col"></th>
                        </tr>
                    }
                </thead>
                <tbody>
                    @if (Model.employees != null)
                    {
                        @foreach (var item in Model.employees)
                        {
                            <tr>

                                @foreach (var col in item)
                                {
                                    <td><p>@col.Value</p></td>
                                }

                                @if (item["Код"] != null)
                                {
                                    <td class="text-end" nowrap>
                                        <a asp-controller="ProjectManager" asp-action="UpdateDeveloper" asp-route-id=@int.Parse(item["Код"]) asp-route-projectid=@Model.selectedProject["Код"] class="btn btn-dark">
                                            <i class="bi bi-pencil-fill"></i>
                                        </a>
                                    </td>
                                }
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

        @if (Model.selectedProject != null)
        {
            <div class="row">

                <div class="col-6 text-start">
                    <a asp-controller="ProjectManager" asp-action="GetAllTasks" asp-route-projectid=@int.Parse(Model.selectedProject["Код"]) class="btn btn-dark">
                        Посмотреть все трудозатраты
                    </a>
                </div>
                <div class="col-6 text-end">
                    <a asp-controller="ProjectManager" asp-action="AvailableEmployees" asp-route-projectid=@int.Parse(Model.selectedProject["Код"]) class="btn btn-dark">
                        Добавить разработчика
                    </a>
                </div>
            </div>
        }
    </div>

    <div class="col-1"></div>
</div>

Practice/Views/ProjectManager/UpdateDeveloper.cshtml
@model Dictionary<string, string>
@{
    ViewData["Title"] = "UpdateDeveloper";
}

<div class="row">
    <h1 class="mt-3 mb-3">Менеджер проекта</h1>
</div>

<div class="container">
    <div class="row align-middle">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="row">
                <div class="col mt-4 login-font">
                    <h2 class="mt-2 mb-4 text-center">Информация о разработчике</h2>
                    <table class="table table-striped">
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Key</td>
                                    <td>@item.Value</td>

                                    <td>
                                        @switch (item.Key)
                                        {
                                            case "Роль":
                                                <a asp-controller="ProjectManager" asp-action="UpdateRole" asp-route-id=@int.Parse(Model["Код"]) asp-route-projectid=@ViewBag.ProjectId class="btn btn-dark">
                                                    <i class="bi bi-pencil-fill"></i>
                                                </a>
                                                break;
                                            case "Ставка":
                                                <a asp-controller="ProjectManager" asp-action="UpdateRate" asp-route-id=@int.Parse(Model["Код"]) asp-route-projectid=@ViewBag.ProjectId class="btn btn-dark">
                                                    <i class="bi bi-pencil-fill"></i>
                                                </a>
                                                break;
                                            case "ДатаОкончанияРаботыНаПроекте":
                                                <a asp-controller="ProjectManager" asp-action="UpdateEndDate" asp-route-id=@int.Parse(Model["Код"]) asp-route-projectid=@ViewBag.ProjectId class="btn btn-dark">
                                                    <i class="bi bi-pencil-fill"></i>
                                                </a>
                                                break;
                                            default:
                                                break;
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="row">
                <div class="col-4 text-start">
                    <a asp-controller="ProjectManager" asp-action="GetAllRates" asp-route-id=@int.Parse(Model["Код"]) asp-route-projectid=@ViewBag.ProjectId class="btn btn-dark" style="width:200px">
                        История ставок
                    </a>
                </div>
                <div class="col-8 text-end">
                   <a asp-controller="ProjectManager" asp-action="Index" asp-route-projectid=@ViewBag.ProjectId class="btn btn-secondary" style="width:150px">
                    Назад
                </a>
                </div>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</div>

Practice/Views/ProjectManager/UpdateEndDate.cshtml
@model ПроектыИСотрудники
@{
    ViewData["Title"] = "UpdateEndDate";
}

<div class="row">
    <h1 class="mt-3 mb-3">Менеджер проекта</h1>
</div>

<form method="post" asp-action="UpdateEndDate">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2 class="text_primary">Изменение даты окончания работы на проекте</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="КодСотрудника">Код сотрудника</label>
                <input asp-for="КодСотрудника" class="form-control" value=@Model.КодСотрудника readonly />
            </div>
            <div class="mb-3">
                <label asp-for="КодПроекта">Код проекта</label>
                <input asp-for="КодПроекта" class="form-control" value=@Model.КодПроекта readonly />
            </div>
            <div class="mb-3">
                <label asp-for="ДатаНачалаРаботыНаПроекте">Дата начала работы на проекте</label>
                <input asp-for="ДатаНачалаРаботыНаПроекте" class="form-control" type="datetime" value=@Model.ДатаНачалаРаботыНаПроекте readonly />
            </div>
            <div class="mb-3">
                <label asp-for="КодРоли">Код роли</label>
                <input asp-for="КодРоли" class="form-control" value=@Model.КодРоли readonly />
            </div>
            <div class="mb-3">
                <label>Дата окончания работы на проекте</label>
                @if (Model.ДатаОкончанияРаботыНаПроекте == null)
                {
                    <input class="form-control" readonly />
                }
                else
                {
                    <input type="date" class="form-control" value=@Model.ДатаОкончанияРаботыНаПроекте readonly />
                }
                
            </div>

            <div class="mb-3">
                <label asp-for="ДатаОкончанияРаботыНаПроекте">Новая дата окончания работы на проекте</label>
                <input asp-for="ДатаОкончанияРаботыНаПроекте" class="form-control" />
                
            </div>

            <div class="text-end">
                <a asp-controller="ProjectManager" asp-action="UpdateDeveloper" asp-route-id=@Model.КодСотрудника asp-route-projectid=@Model.КодПроекта class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Отправить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>