Practice/Controllers/DbAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Practice.Models;
using Practice.Data;
using Newtonsoft.Json;

namespace Practice.Controllers
{
    [Authorize(Roles = "Администратор баз данных")]
    public class DbAdminController : Controller
    {
        public IActionResult Index(string tableName = "")
        {
            if (tableName != "")
            {
                var tables = new string[] { "Виды трудоустройства", "Должности", "Пол", "Роли", "Статусы", "Типы проектов" };

                if (!tables.Contains(tableName))
                    return NotFound();

                var table = new List<Dictionary<string, string>>();

                using (var db = new CourseProject2DBContext())
                {
                    switch (tableName)
                    {
                        case "Виды трудоустройства":
                            var query1 = from item in db.ВидыТрудоустройстваs
                                         select new
                                         {
                                             item.Код,
                                             item.ВидТрудоустройства
                                         };

                            foreach (var item in query1)
                            {
                                var json = JsonConvert.SerializeObject(item);
                                table.Add(JsonConvert.DeserializeObject<Dictionary<string, string>>(json));
                            }

                            if (table.Count == 0)
                                table.Add(new Dictionary<string, string>() { { "Код", null }, { "ВидТрудоустройства", null } });
                            break;
                        case "Должности":
                            var query2 = from item in db.Должностиs
                                         select new
                                         {
                                             item.Код,
                                             item.Должность
                                         };

                            foreach (var item in query2)
                            {
                                var json = JsonConvert.SerializeObject(item);
                                table.Add(JsonConvert.DeserializeObject<Dictionary<string, string>>(json));
                            }

                            if (table.Count == 0)
                                table.Add(new Dictionary<string, string>() { { "Код", null }, { "Должность", null } });
                            break;
                        case "Пол":
                            var query3 = from item in db.Полs
                                         select new
                                         {
                                             item.Код,
                                             Пол = item.Пол1
                                         };

                            foreach (var item in query3)
                            {
                                var json = JsonConvert.SerializeObject(item);
                                table.Add(JsonConvert.DeserializeObject<Dictionary<string, string>>(json));
                            }

                            if (table.Count == 0)
                                table.Add(new Dictionary<string, string>() { { "Код", null }, { "Пол", null } });
                            break;
                        case "Роли":
                            var query4 = from item in db.Ролиs
                                         select new
                                         {
                                             item.Код,
                                             item.Роль
                                         };

                            foreach (var item in query4)
                            {
                                var json = JsonConvert.SerializeObject(item);
                                table.Add(JsonConvert.DeserializeObject<Dictionary<string, string>>(json));
                            }

                            if (table.Count == 0)
                                table.Add(new Dictionary<string, string>() { { "Код", null }, { "Роль", null } });
                            break;
                        case "Статусы":
                            var query5 = from item in db.Статусыs
                                         select new
                                         {
                                             item.Код,
                                             item.Статус
                                         };

                            foreach (var item in query5)
                            {
                                var json = JsonConvert.SerializeObject(item);
                                table.Add(JsonConvert.DeserializeObject<Dictionary<string, string>>(json));
                            }

                            if (table.Count == 0)
                                table.Add(new Dictionary<string, string>() { { "Код", null }, { "Статус", null } });
                            break;
                        case "Типы проектов":
                            var query6 = from item in db.ТипыПроектовs
                                         select new
                                         {
                                             item.Код,
                                             item.ТипПроекта
                                         };

                            foreach (var item in query6)
                            {
                                var json = JsonConvert.SerializeObject(item);
                                table.Add(JsonConvert.DeserializeObject<Dictionary<string, string>>(json));
                            }

                            if (table.Count == 0)
                                table.Add(new Dictionary<string, string>() { { "Код", null }, { "ТипПроекта", null } });
                            break;
                    }

                    ViewBag.TableName = tableName;

                    return View(table);
                }
            }

            return View();
        }

        public IActionResult AddItem(string tableName = "")
        {
            switch (tableName)
            {
                case "Виды трудоустройства":
                    return RedirectToAction("AddEmpType");
                case "Должности":
                    return RedirectToAction("AddPosition");
                case "Пол":
                    return RedirectToAction("AddGender");
                case "Роли":
                    return RedirectToAction("AddRole");
                case "Статусы":
                    return RedirectToAction("AddStatus");
                case "Типы проектов":
                    return RedirectToAction("AddProjectType");
                default:
                    return NotFound();
            }
        }

        [HttpGet]
        public IActionResult AddEmpType()
        {
            return View(new ВидыТрудоустройства());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddEmpType(ВидыТрудоустройства empType)
        {
            using (var db = new CourseProject2DBContext())
            {
                if (ModelState.ErrorCount == 1)
                {
                    db.ВидыТрудоустройстваs.Add(empType);
                    db.SaveChanges();

                    return RedirectToAction("Index", new { tableName = "Виды трудоустройства" });
                }
            }

            return View(empType);
        }

        [HttpGet]
        public IActionResult AddPosition()
        {
            return View(new Должности());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPosition(Должности pos)
        {
            using (var db = new CourseProject2DBContext())
            {
                if (ModelState.ErrorCount == 1)
                {
                    db.Должностиs.Add(pos);
                    db.SaveChanges();

                    return RedirectToAction("Index", new { tableName = "Должности" });
                }
            }

            return View(pos);
        }

        [HttpGet]
        public IActionResult AddGender()
        {
            return View(new Пол());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddGender(Пол sex)
        {
            using (var db = new CourseProject2DBContext())
            {
                if (ModelState.ErrorCount == 1)
                {
                    db.Полs.Add(sex);
                    db.SaveChanges();

                    return RedirectToAction("Index", new { tableName = "Пол" });
                }
            }

            return View(sex);
        }

        [HttpGet]
        public IActionResult AddRole()
        {
            return View(new Роли());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddRole(Роли role)
        {
            using (var db = new CourseProject2DBContext())
            {
                if (ModelState.ErrorCount == 1)
                {
                    db.Ролиs.Add(role);
                    db.SaveChanges();

                    return RedirectToAction("Index", new { tableName = "Роли" });
                }
            }

            return View(role);
        }

        [HttpGet]
        public IActionResult AddStatus()
        {
            return View(new Статусы());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddStatus(Статусы status)
        {
            using (var db = new CourseProject2DBContext())
            {
                if (ModelState.ErrorCount == 1)
                {
                    db.Статусыs.Add(status);
                    db.SaveChanges();

Practice/Views/DbAdmin/AddEmpType.cshtml
@model ВидыТрудоустройства
@{
    ViewData["Title"] = "AddEmpType";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="AddEmpType">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Добавление вида трудоустройства</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="ВидТрудоустройства">Вид трудоустройства</label>
                <input asp-for="ВидТрудоустройства" class="form-control" value=@Model.ВидТрудоустройства />
                <span asp-validation-for="ВидТрудоустройства" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Виды трудоустройства" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Добавить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/AddGender.cshtml
@model Пол
@{
    ViewData["Title"] = "AddGender";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="AddGender">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Добавление пола</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Пол1">Пол</label>
                <input asp-for="Пол1" class="form-control" value=@Model.Пол1 />
                <span asp-validation-for="Пол1" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Пол" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Добавить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/AddPosition.cshtml
@model Должности
@{
    ViewData["Title"] = "AddPosition";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="AddPosition">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Добавление должности</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Должность">Должность</label>
                <input asp-for="Должность" class="form-control" value=@Model.Должность />
                <span asp-validation-for="Должность" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Должности" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Добавить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/DeleteGender.cshtml
@model Пол
@{
    ViewData["Title"] = "DeleteGender";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="DeleteGender">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Удаление пола</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="Пол1">Пол</label>
                <input asp-for="Пол1" class="form-control" value=@Model.Пол1 readonly />
                <span asp-validation-for="Пол1" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Пол" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Удалить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/DeletePosition.cshtml
@model Должности
@{
    ViewData["Title"] = "DeletePosition";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="DeletePosition">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Удаление должности</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="Должность">Должность</label>
                <input asp-for="Должность" class="form-control" value=@Model.Должность readonly />
                <span asp-validation-for="Должность" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Должности" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Удалить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/DeleteRole.cshtml
@model Роли
@{
    ViewData["Title"] = "DeleteRole";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="DeleteRole">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Удаление роли</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="Роль">Роль</label>
                <input asp-for="Роль" class="form-control" value=@Model.Роль readonly />
                <span asp-validation-for="Роль" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Роли" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Удалить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/DeleteStatus.cshtml
@model Статусы
@{
    ViewData["Title"] = "DeleteStatus";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="DeleteStatus">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Удаление статуса</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="Статус">Статус</label>
                <input asp-for="Статус" class="form-control" value=@Model.Статус readonly />
                <span asp-validation-for="Статус" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Статусы" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Удалить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/DeletionForbidden.cshtml
@{
    ViewData["Title"] = "DeletionForbidden";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<h4 class="text-center mt-5">Удаление данного объекта невозможно, поскольку на него существуют ссылки в базе данных!</h4>

Practice/Views/DbAdmin/Index.cshtml
@model List<Dictionary<string, string>>
@{
    ViewData["Title"] = "Index";
    ViewBag.Tables = new string[] { "Виды трудоустройства", "Должности", "Пол", "Роли", "Статусы", "Типы проектов" };
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<div class="row">
    <div class="col-2">
        <a class="nav-link dropdown-toggle active text-dark h4" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Таблицы</a>
        <div class="dropdown-menu">
            @foreach (var item in ViewBag.Tables)
            {
                <a class="dropdown-item" asp-controller="DbAdmin" asp-action="Index" asp-route-tableName=@item>@item</a>
            }
        </div>
    </div>

    <div class="col-10">
        @if (Model != null)
        {
            <h4 class="mt-2">@ViewBag.TableName</h4>
        }
        <div>
            <table class="table align-middle table-striped ">
                <thead>
                    @if (Model != null)
                    {
                        <tr>
                            @foreach (var item in Model[0].Keys)
                            {
                                <th scope="col">@item</th>
                            }
                            <th scope="col"></th>
                        </tr>
                    }
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>

                                @foreach (var col in item)
                                {
                                    <td><p>@col.Value</p></td>
                                }

                                @if (item["Код"] != null)
                                {
                                    <td class="text-end" nowrap>
                                        <a asp-controller="DbAdmin" asp-action="UpdateItem" asp-route-tableName=@ViewBag.TableName asp-route-id=@item["Код"] class="btn btn-dark">
                                            <i class="bi bi-pencil-fill"></i>
                                        </a>
                                        <a asp-controller="DbAdmin" asp-action="DeleteItem" asp-route-tableName=@ViewBag.TableName asp-route-id=@int.Parse(item["Код"]) class="btn btn-dark">
                                            <i class="bi bi-trash3-fill"></i>
                                        </a>
                                    </td>
                                }
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

        @if (Model != null)
        {
            <div class="row">
                <div class="text-end">
                    <a asp-controller="DbAdmin" asp-action="AddItem" asp-route-tableName=@ViewBag.TableName class="btn btn-dark">
                        Добавить
                    </a>
                </div>
            </div>
        }
    </div>
</div>

Practice/Views/DbAdmin/UpdateEmpType.cshtml
@model ВидыТрудоустройства
@{
    ViewData["Title"] = "UpdateEmpType";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="UpdateEmpType">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Обновление вида трудоустройства</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="ВидТрудоустройства">Вид трудоустройства</label>
                <input asp-for="ВидТрудоустройства" class="form-control" value=@Model.ВидТрудоустройства />
                <span asp-validation-for="ВидТрудоустройства" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Виды трудоустройства" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Обновить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/UpdateGender.cshtml
@model Пол
@{
    ViewData["Title"] = "UpdateGender";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="UpdateGender">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Обновление пола</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="Пол1">Пол</label>
                <input asp-for="Пол1" class="form-control" value=@Model.Пол1 />
                <span asp-validation-for="Пол1" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Пол" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Обновить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/UpdatePosition.cshtml
@model Должности
@{
    ViewData["Title"] = "UpdatePosition";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="UpdatePosition">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Обновление должности</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="Должность">Должность</label>
                <input asp-for="Должность" class="form-control" value=@Model.Должность />
                <span asp-validation-for="Должность" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Должности" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Обновить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/UpdateProjectType.cshtml
@model ТипыПроектов
@{
    ViewData["Title"] = "UpdateProjectType";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="UpdateProjectType">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Обновление типа проекта</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="ТипПроекта">Тип проекта</label>
                <input asp-for="ТипПроекта" class="form-control" value=@Model.ТипПроекта />
                <span asp-validation-for="ТипПроекта" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Типы проектов" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Обновить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>

Practice/Views/DbAdmin/UpdateRole.cshtml
@model Роли
@{
    ViewData["Title"] = "UpdateRole";
}

<div class="row">
    <h1 class="mt-3 mb-3">Администратор баз данных</h1>
</div>

<form method="post" asp-action="UpdateRole">
    <div class="row">
        <div class="col-3"></div>
        <div class="border p-3 mt-4 col-6">
            <div class="row pb-2">
                <h2>Обновление роли</h2>
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Код">Код</label>
                <input asp-for="Код" class="form-control" value=@Model.Код readonly />
            </div>
            <div class="mb-3">
                <label asp-for="Роль">Роль</label>
                <input asp-for="Роль" class="form-control" value=@Model.Роль />
                <span asp-validation-for="Роль" class="text-danger"></span>
            </div>

            <div class="text-end">
                <a asp-controller="DbAdmin" asp-action="Index" asp-route-tableName="Роли" class="btn btn-secondary mx-3" style="width:150px">
                    Назад
                </a>
                <button type="submit" class="btn btn-dark" style="width:150px">
                    Обновить
                </button>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</form>